# Generated by Django 5.2.4 on 2025-07-24 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMBC_Check_Sheet_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinderBody', models.CharField(max_length=100)),
                ('pistonTrunnion', models.CharField(max_length=100)),
                ('adjustingTube', models.CharField(max_length=100)),
                ('plungerSpring', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bogie_Check_Sheet_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieFrameCondition', models.CharField(max_length=100)),
                ('bolster', models.CharField(max_length=100)),
                ('bolsterSuspensionBracket', models.CharField(max_length=100)),
                ('lowerSpringSeat', models.CharField(max_length=100)),
                ('axleGuide', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bogie_Details_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieNo', models.CharField(max_length=50)),
                ('makerYearBuilt', models.CharField(max_length=100)),
                ('incomingDivAndDate', models.CharField(max_length=100)),
                ('deficitComponents', models.TextField()),
                ('dateOfIOH', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Wheel_Specification_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treadDiameterNew', models.CharField(max_length=100)),
                ('lastShopIssueSize', models.CharField(max_length=100)),
                ('condemningDia', models.CharField(max_length=100)),
                ('wheelGauge', models.CharField(max_length=100)),
                ('variationSameAxle', models.CharField(max_length=50)),
                ('variationSameBogie', models.CharField(max_length=50)),
                ('variationSameCoach', models.CharField(max_length=50)),
                ('wheelProfile', models.CharField(max_length=100)),
                ('intermediateWWP', models.CharField(max_length=100)),
                ('bearingSeatDiameter', models.CharField(max_length=100)),
                ('rollerBearingOuterDia', models.CharField(max_length=100)),
                ('rollerBearingBoreDia', models.CharField(max_length=100)),
                ('rollerBearingWidth', models.CharField(max_length=100)),
                ('axleBoxHousingBoreDia', models.CharField(max_length=100)),
                ('wheelDiscWidth', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bogie_Check_Sheet_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50, unique=True)),
                ('inspectionBy', models.CharField(max_length=100)),
                ('inspectionDate', models.DateField()),
                ('bmbcChecksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspectionData.bmbc_check_sheet_data', verbose_name='BMBC Check Sheet')),
                ('bogieChecksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspectionData.bogie_check_sheet_data', verbose_name='Bogie Check Sheet')),
                ('bogieDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspectionData.bogie_details_data', verbose_name='Bogie Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wheel_Specification_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50, unique=True)),
                ('submittedBy', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspectionData.wheel_specification_data', verbose_name='Fields')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
